### ISSUE TITLE
Node colors

### ISSUE THREAD

**Issue by AngeloLupo** [Dynamic-Underground-Strippers/TaxE#35]
![image](https://cloud.githubusercontent.com/assets/1773740/5818683/61d60546-a0af-11e4-8c5d-488284d0498d.png)

In this situation no node is marked in blue, can be confusing.

Also when a node is both start and end (of two goals) is marked just as one of the two.

**Comment by Ezard** [comment]
Blue is the end node, and when you click on it all of the circles disappear anyway because the route has been assigned
And Matt has changed the code so goals can't share any nodes, no matter whether they're start nodes or end nodes

**Comment by AngeloLupo** [comment]
Matt's changes aren't working :(
When a node marked as part of a route (ie green) it will not be marked in blue also if it is actually possible to select it as next node in the route

**Comment by AngeloLupo** [comment]
Also all the start and end node for each goal are marked at the same time, and the player can't tell which is which without reading
